import { StyleSheet } from 'react-native';
import { colors } from './constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'flex-start',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 20,
  },
  scrollContentWithBottomNav: {
    paddingBottom: 120,
  },
  listContent: {
    paddingBottom: 20,
  },

  // Header Styles
  header: {
    backgroundColor: colors.primary,
    paddingTop: 20,
    paddingBottom: 24,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    pointerEvents: 'auto',
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  headerSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 4,
    fontWeight: '500',
  },
  userSection: {
    alignItems: 'flex-end',
    pointerEvents: 'auto',
  },
  username: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  logoutButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    cursor: 'pointer',
    pointerEvents: 'auto',
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },

  // Page Header (for creation pages)
  pageHeader: {
    backgroundColor: colors.primary,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  closeButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 24,
    color: '#FFFFFF',
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  pageSubtitle: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 2,
  },
  headerSpacer: {
    width: 40,
  },

  // Category Header
  categoryHeader: {
    backgroundColor: colors.primary,
    paddingTop: 16,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  backHeaderButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  backHeaderButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  categoryHeaderContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
  },
  categoryHeaderEmoji: {
    fontSize: 28,
    marginRight: 12,
  },
  categoryHeaderTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  categoryHeaderCount: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },

  // Page Content
  pageContent: {
    flex: 1,
    zIndex: 1,
  },

  // Input Styles
  inputGroup: {
    marginHorizontal: 16,
    marginBottom: 20,
  },
  label: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
  },
  textAreaInput: {
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
    minHeight: 120,
  },
  charCount: {
    fontSize: 12,
    color: colors.lightText,
    marginTop: 6,
    textAlign: 'right',
  },

  // Radio Button Styles
  radioGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  radioOption: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  radioCircleSelected: {
    borderColor: colors.primary,
  },
  radioCircleInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.primary,
  },
  radioLabel: {
    fontSize: 16,
    color: colors.text,
  },

  // Date Range Picker Styles
  dateRangeContainer: {
    gap: 14,
  },
  dateRangeSection: {
    gap: 8,
  },
  dateRangeLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.lightText,
  },
  datePickerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateNavButton: {
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 8,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateNavText: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: 'bold',
  },
  dateDisplay: {
    flex: 1,
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    justifyContent: 'center',
  },
  dateDisplayActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(46, 80, 144, 0.05)',
  },
  dateDisplayText: {
    fontSize: 16,
    color: colors.text,
    fontWeight: '500',
  },
  dateConfirmButton: {
    backgroundColor: colors.secondary,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  dateConfirmText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },

  // Price Input Styles
  priceInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
  },
  priceSymbol: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginRight: 8,
  },
  priceInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    color: colors.text,
  },

  // Image Upload Styles
  imageUploadArea: {
    backgroundColor: colors.lightBg,
    borderWidth: 2,
    borderColor: colors.border,
    borderStyle: 'dashed',
    borderRadius: 10,
    paddingVertical: 40,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 200,
  },
  imageUploadIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  imageUploadText: {
    fontSize: 16,
    color: colors.lightText,
  },
  imagePreviewContainer: {
    position: 'relative',
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 12,
  },
  imagePreview: {
    width: '100%',
    height: 180,
    borderRadius: 10,
  },
  imageRemoveButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  imageRemoveButtonText: {
    fontSize: 24,
    color: colors.secondary,
    fontWeight: 'bold',
  },
  imageButtonContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  imageButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 10,
    gap: 8,
  },
  imageButtonSecondary: {
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  imageButtonIcon: {
    fontSize: 20,
  },
  imageButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },

  // Button Styles
  buttonContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  buttonContainerAboveBottomNav: {
    paddingBottom: 100,
    marginBottom: 0,
  },
  nextButton: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  nextButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  backButton: {
    flex: 0.35,
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  submitButton: {
    flex: 0.65,
    backgroundColor: colors.success,
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  submitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },

  // Home Page Specific Styles
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 16,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text,
  },

  // Borough Filter Styles
  boroughFilterContainer: {
    marginHorizontal: 16,
    marginBottom: 16,
  },
  boroughFilterLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 10,
  },
  boroughScrollContent: {
    paddingRight: 16,
  },
  boroughFilterButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    marginRight: 8,
  },
  boroughFilterButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  boroughFilterButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  boroughFilterButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  boroughScrollWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  boroughScrollArrow: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.primary,
    paddingHorizontal: 6,
  },

  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginLeft: 16,
    marginBottom: 12,
  },

  // Category Styles
  categoriesGrid: {
    flexDirection: 'row',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  categoriesGridContent: {
    paddingRight: 8,
  },
  categoryCard: {
    width: 182,
    height: 70,
    backgroundColor: colors.background,
    marginRight: 8,
    padding: 6,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  categoryCardEmoji: {
    fontSize: 22,
    marginBottom: 2,
  },
  categoryCardName: {
    fontSize: 10,
    color: colors.text,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 12,
  },

  // Object Grid Styles
  objectsGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
  },
  objectGridItem: {
    width: '48%',
    margin: '1%',
    marginBottom: 16,
  },
  objectGridItemDesktop: {
    width: '31%',
  },
  objectCard: {
    backgroundColor: colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  objectCardImage: {
    width: '100%',
    height: 100,
    backgroundColor: colors.lightBg,
    resizeMode: 'contain',
  },
  objectCardContent: {
    padding: 12,
  },
  objectCardName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  objectCardCondition: {
    fontSize: 12,
    color: colors.lightText,
    marginBottom: 8,
  },
  objectCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  objectCardPrice: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.primary,
  },
  deleteButton: {
    position: 'absolute',
    top: 5,
    right: 5,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E74C3C',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    zIndex: 10,
  },
  deleteButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.background,
  },

  // Empty State
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    paddingHorizontal: 30,
  },
  emptyStateEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateText: {
    fontSize: 14,
    color: colors.lightText,
    textAlign: 'center',
  },

  // Navigation Styles
  homeContainerMobile: {
    flex: 1,
    backgroundColor: colors.background,
    paddingBottom: 72,
  },
  homeContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: colors.background,
  },
  homeContent: {
    flex: 1,
    flexDirection: 'column',
    position: 'relative',
  },
  bottomNavBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 10,
    paddingBottom: 16,
    paddingHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 12,
    zIndex: 100,
  },
  bottomNavItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    borderRadius: 10,
  },
  bottomNavItemActive: {
    backgroundColor: 'rgba(46, 80, 144, 0.12)',
  },
  bottomNavIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  bottomNavLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.lightText,
  },
  bottomNavLabelActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  bottomSpacing: {
    height: 96,
  },

  // Left Sidebar Styles
  leftSidebar: {
    width: 80,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  sidebarBrand: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  sidebarBrandText: {
    fontSize: 24,
    fontWeight: '800',
    color: '#fff',
  },
  sidebarNav: {
    gap: 16,
  },
  sidebarNavItem: {
    width: 60,
    height: 60,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
  sidebarNavItemActive: {
    backgroundColor: colors.secondary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  sidebarNavIcon: {
    fontSize: 28,
    marginBottom: 4,
  },
  sidebarNavLabel: {
    fontSize: 10,
    color: '#fff',
    fontWeight: '600',
    textAlign: 'center',
  },

  // Category Grid Styles
  categoryGridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  categoryGridItem: {
    width: '20%',
    aspectRatio: 1,
    borderRadius: 10,
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  categoryGridItemSelected: {
    backgroundColor: 'rgba(46, 80, 144, 0.1)',
    borderColor: colors.primary,
    borderWidth: 2,
  },
  categoryGridEmoji: {
    fontSize: 18,
  },
  categoryGridLabel: {
    fontSize: 8,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  categoryGridLabelSelected: {
    color: colors.primary,
    fontWeight: '700',
  },

  // Product Detail Styles
  detailImageContainer: {
    width: '100%',
    height: 300,
    marginBottom: 16,
    borderRadius: 12,
    overflow: 'hidden',
  },
  detailImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  detailCard: {
    marginHorizontal: 16,
    marginBottom: 20,
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  detailHeader: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  detailTitleSection: {
    gap: 8,
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
  },
  detailPrice: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.primary,
  },
  detailInfoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  detailInfoItem: {
    width: '50%',
    paddingHorizontal: 4,
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.border,
  },
  detailInfoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightText,
    marginBottom: 6,
    textAlign: 'center',
  },
  detailInfoValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'center',
  },
  detailSection: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 12,
  },
  detailDescription: {
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
  },
  detailOwnerCard: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.lightBg,
  },
  ownerInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  ownerAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ownerAvatarText: {
    fontSize: 28,
  },
  ownerDetails: {
    flex: 1,
  },
  ownerLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightText,
    marginBottom: 4,
  },
  ownerName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },
  ownerArrow: {
    fontSize: 18,
    color: colors.secondary,
    fontWeight: '700',
  },
  detailActionButton: {
    marginHorizontal: 16,
    marginVertical: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  detailActionButtonIcon: {
    fontSize: 20,
  },
  detailActionButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  detailReportButton: {
    backgroundColor: '#E74C3C',
    borderColor: '#E74C3C',
    shadowColor: '#E74C3C',
  },
  detailRateSellerButton: {
    marginHorizontal: 16,
    marginTop: 4,
    marginBottom: 0,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  detailRateSellerButtonDisabled: {
    opacity: 0.55,
    borderColor: colors.border,
  },
  detailRateSellerIcon: {
    fontSize: 18,
  },
  detailRateSellerText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },

  // Review Modal Styles
  reviewModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(44, 62, 80, 0.45)',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  reviewModalAvoid: {
    width: '100%',
  },
  reviewModalCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  reviewModalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 4,
  },
  reviewModalSubtitle: {
    fontSize: 14,
    color: colors.lightText,
    marginBottom: 16,
  },
  reviewStarsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
  },
  reviewStarHit: {
    padding: 6,
  },
  reviewStarEmoji: {
    fontSize: 32,
  },
  reviewStarEmojiDim: {
    opacity: 0.22,
  },
  reviewModalLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  reviewModalInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
    minHeight: 100,
    textAlignVertical: 'top',
    backgroundColor: colors.lightBg,
    marginBottom: 8,
  },
  reviewCommentCount: {
    fontSize: 12,
    color: colors.lightText,
    textAlign: 'right',
    marginBottom: 20,
  },
  reviewModalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  reviewModalCancel: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.lightBg,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
  },
  reviewModalCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.text,
  },
  reviewModalSubmit: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  reviewModalSubmitDisabled: {
    opacity: 0.7,
  },
  reviewModalSubmitText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },

  // Profile Styles
  profileSummaryCard: {
    marginHorizontal: 16,
    marginTop: 16,
    padding: 18,
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileRatingRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  profileRatingStars: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.primary,
  },
  profileRatingMeta: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.lightText,
  },
  profileEmail: {
    fontSize: 14,
    color: colors.text,
  },
  profileSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 12,
  },
  profileReviewsList: {
    flex: 1,
  },
  profileReviewsListContent: {
    paddingHorizontal: 16,
    paddingBottom: 96,
  },
  profileReviewCard: {
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 12,
  },
  profileReviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    gap: 8,
  },
  profileReviewName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: colors.primary,
  },
  profileReviewDate: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.lightText,
  },
  profileReviewStars: {
    fontSize: 14,
    marginBottom: 8,
  },
  profileReviewComment: {
    fontSize: 15,
    color: colors.text,
    lineHeight: 22,
  },
  profileEmptyReviews: {
    marginHorizontal: 24,
    marginTop: 24,
    alignItems: 'center',
  },
  profileEmptyEmoji: {
    fontSize: 40,
    marginBottom: 8,
  },
  profileEmptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 6,
  },
  profileEmptyText: {
    fontSize: 14,
    color: colors.lightText,
    textAlign: 'center',
    lineHeight: 20,
  },

  // Seller Profile Styles
  sellerProfileCard: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 24,
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  sellerHeaderSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 16,
  },
  sellerAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sellerAvatarText: {
    fontSize: 32,
  },
  sellerNameSection: {
    flex: 1,
  },
  sellerName: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 6,
  },
  sellerRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sellerRating: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
  },
  sellerReviewCount: {
    fontSize: 14,
    color: colors.lightText,
    fontWeight: '600',
  },
  sellerContactInfo: {
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 12,
    gap: 8,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  contactIcon: {
    fontSize: 18,
  },
  contactText: {
    fontSize: 14,
    color: colors.text,
    flex: 1,
  },
  sellerItemsGrid: {
    marginHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  sellerItemCard: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  sellerItemImage: {
    width: 100,
    height: 100,
  },
  sellerItemContent: {
    flex: 1,
    padding: 12,
    justifyContent: 'space-between',
  },
  sellerItemName: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  sellerItemPrice: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.secondary,
  },

  // Safety Guidelines Styles
  safetyHeader: {
    backgroundColor: colors.primary,
    paddingTop: 20,
    paddingBottom: 24,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  safetyHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  safetyHeaderIcon: {
    fontSize: 40,
  },
  safetyHeaderText: {
    flex: 1,
  },
  safetyTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  safetySubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    marginTop: 4,
    fontWeight: '500',
  },
  safetyContent: {
    flex: 1,
  },
  safetyIntro: {
    marginHorizontal: 16,
    marginTop: 24,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: colors.lightBg,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: colors.accent,
  },
  safetyIntroText: {
    fontSize: 15,
    color: colors.text,
    lineHeight: 24,
    fontWeight: '500',
  },
  safetyTipsContainer: {
    marginHorizontal: 16,
    marginTop: 24,
    marginBottom: 24,
    gap: 14,
  },
  safetyTipCard: {
    backgroundColor: colors.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  safetyTipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  safetyTipIconContainer: {
    position: 'relative',
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  safetyTipCircleNumber: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    textAlignVertical: 'center',
    top: 0,
    right: 0,
    zIndex: 10,
  },
  safetyTipIcon: {
    fontSize: 32,
  },
  safetyTipTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  safetyTipDescription: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 22,
    marginBottom: 12,
  },
  safetyHighlight: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(26, 188, 156, 0.08)',
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  safetyHighlightText: {
    fontSize: 13,
    color: colors.text,
    lineHeight: 20,
    fontWeight: '500',
  },
  safetyCtaContainer: {
    marginHorizontal: 16,
    marginBottom: 40,
  },
  safetyCtaBox: {
    backgroundColor: colors.accent,
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  safetyCtaIcon: {
    fontSize: 48,
    marginBottom: 12,
  },
  safetyCtaTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  safetyCtaText: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 22,
    textAlign: 'center',
  },

  // Misc
  spacer: {
    height: 30,
  },
});
